import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Dashboard</Link>
        </li>
        <li>
          <Link to="/dashboardtwo">DashboardTwo</Link>
        </li>
        <li>
          <Link to="/users">Users</Link>
        </li>
        <li>
          <Link to="/userstats">UserStats</Link>
        </li>
        <li>
          <Link to="/activities">Activities</Link>
        </li>
        <li>
          <Link to="/settings">Settings</Link>
        </li>
        <li>
          <Link to="/dashboardone">DashboardOne</Link>
        </li>
        <li>
          <Link to="/documenttwo">DocumentTwo</Link>
        </li>
        <li>
          <Link to="/messageone">MessageOne</Link>
        </li>
        <li>
          <Link to="/login">Login</Link>
        </li>
        <li>
          <Link to="/selected">Selected</Link>
        </li>
        <li>
          <Link to="/employeeone">EmployeeOne</Link>
        </li>
        <li>
          <Link to="/signupone">SignupOne</Link>
        </li>
        <li>
          <Link to="/activitiesone">ActivitiesOne</Link>
        </li>
        <li>
          <Link to="/groups">Groups</Link>
        </li>
        <li>
          <Link to="/employeeshifts">EmployeeShifts</Link>
        </li>
        <li>
          <Link to="/tutorialstwo">TutorialsTwo</Link>
        </li>
        <li>
          <Link to="/helpcentertwo">HelpCenterTwo</Link>
        </li>
        <li>
          <Link to="/taskstwo">TasksTwo</Link>
        </li>
        <li>
          <Link to="/addnewtaskone">AddNewTaskOne</Link>
        </li>
        <li>
          <Link to="/settingsone">SettingsOne</Link>
        </li>
        <li>
          <Link to="/requestone">RequestOne</Link>
        </li>
        <li>
          <Link to="/settingsbilings">SettingsBilings</Link>
        </li>
        <li>
          <Link to="/settingsadmins">SettingsAdmins</Link>
        </li>
        <li>
          <Link to="/dashboardsix">DashboardSix</Link>
        </li>
        <li>
          <Link to="/bookingstasktwo">BookingstaskTwo</Link>
        </li>
        <li>
          <Link to="/addnewtasktwo">AddnewtaskTwo</Link>
        </li>
        <li>
          <Link to="/trainingone">TrainingOne</Link>
        </li>
        <li>
          <Link to="/updates">Updates</Link>
        </li>
        <li>
          <Link to="/messagefive">MessageFive</Link>
        </li>
        <li>
          <Link to="/bookingsrequestone">BookingsRequestOne</Link>
        </li>
        <li>
          <Link to="/timesheettwo">TimeSheetTwo</Link>
        </li>
        <li>
          <Link to="/timesheetpaidhourstwo">TimeSheetPaidHoursTwo</Link>
        </li>
        <li>
          <Link to="/forms">Forms</Link>
        </li>
        <li>
          <Link to="/helpcenterone">HelpCenterOne</Link>
        </li>
        <li>
          <Link to="/onboardingoneone">OnboardingOneOne</Link>
        </li>
        <li>
          <Link to="/onboardingtwoone">OnboardingTwoOne</Link>
        </li>
        <li>
          <Link to="/clockintwo">ClockinTwo</Link>
        </li>
        <li>
          <Link to="/onboardingone">OnboardingOne</Link>
        </li>
        <li>
          <Link to="/dashboardthree">DashboardThree</Link>
        </li>
        <li>
          <Link to="/bookingstaskone">BookingstaskOne</Link>
        </li>
        <li>
          <Link to="/addnewtask">Addnewtask</Link>
        </li>
        <li>
          <Link to="/training">Training</Link>
        </li>
        <li>
          <Link to="/messagethree">MessageThree</Link>
        </li>
        <li>
          <Link to="/bookingsrequest">BookingsRequest</Link>
        </li>
        <li>
          <Link to="/timesheetone">TimeSheetOne</Link>
        </li>
        <li>
          <Link to="/timesheetpaidhoursone">TimeSheetPaidHoursOne</Link>
        </li>
        <li>
          <Link to="/onboardingtwo">OnboardingTwo</Link>
        </li>
        <li>
          <Link to="/document">Document</Link>
        </li>
        <li>
          <Link to="/clockin">Clockin</Link>
        </li>
        <li>
          <Link to="/message">Message</Link>
        </li>
        <li>
          <Link to="/bookingstask">Bookingstask</Link>
        </li>
        <li>
          <Link to="/documentone">DocumentOne</Link>
        </li>
        <li>
          <Link to="/clockinone">ClockinOne</Link>
        </li>
        <li>
          <Link to="/employee">Employee</Link>
        </li>
        <li>
          <Link to="/addnewbookings">AddnewBookings</Link>
        </li>
        <li>
          <Link to="/employeeprofile">EmployeeProfile</Link>
        </li>
        <li>
          <Link to="/logintwo">LoginTwo</Link>
        </li>
        <li>
          <Link to="/dashboardfive">DashboardFive</Link>
        </li>
        <li>
          <Link to="/calenderone">CalenderOne</Link>
        </li>
        <li>
          <Link to="/requestfornewtask">RequestforNewTask</Link>
        </li>
        <li>
          <Link to="/requestforabsentee">RequestforAbsentee</Link>
        </li>
        <li>
          <Link to="/tutorialsone">TutorialsOne</Link>
        </li>
        <li>
          <Link to="/tasksone">TasksOne</Link>
        </li>
        <li>
          <Link to="/requestforshiftchange">RequestforShiftChange</Link>
        </li>
        <li>
          <Link to="/helpcenter">HelpCenter</Link>
        </li>
        <li>
          <Link to="/request">Request</Link>
        </li>
        <li>
          <Link to="/messagetwo">MessageTwo</Link>
        </li>
        <li>
          <Link to="/settingsnotification">SettingsNotification</Link>
        </li>
        <li>
          <Link to="/timesheet">TimeSheet</Link>
        </li>
        <li>
          <Link to="/timesheetpaidhours">TimeSheetPaidHours</Link>
        </li>
        <li>
          <Link to="/settingsprivacypolicies">SettingsPrivacyPolicies</Link>
        </li>
        <li>
          <Link to="/settingstermsconditions">SettingsTermsConditions</Link>
        </li>
        <li>
          <Link to="/settingsavailibility">SettingsAvailibility</Link>
        </li>
        <li>
          <Link to="/loginone">LoginOne</Link>
        </li>
        <li>
          <Link to="/dashboardfour">DashboardFour</Link>
        </li>
        <li>
          <Link to="/calender">Calender</Link>
        </li>
        <li>
          <Link to="/settingsnotificationone">SettingsNotificationOne</Link>
        </li>
        <li>
          <Link to="/messagefour">MessageFour</Link>
        </li>
        <li>
          <Link to="/signup">Signup</Link>
        </li>
        <li>
          <Link to="/tutorials">Tutorials</Link>
        </li>
        <li>
          <Link to="/tasks">Tasks</Link>
        </li>
        <li>
          <Link to="/settingsprivacypoliciesone">
            SettingsPrivacyPoliciesOne
          </Link>
        </li>
        <li>
          <Link to="/timesheetapproved">TimeSheetApproved</Link>
        </li>
        <li>
          <Link to="/addnewtaskthree">AddNewTaskThree</Link>
        </li>
        <li>
          <Link to="/helpcenterthree">HelpCenterThree</Link>
        </li>
        <li>
          <Link to="/requesttwo">RequestTwo</Link>
        </li>
        <li>
          <Link to="/settingstermsconditionsone">
            SettingsTermsConditionsOne
          </Link>
        </li>
        <li>
          <Link to="/employeetwo">EmployeeTwo</Link>
        </li>
        <li>
          <Link to="/careupdates">CareUpdates</Link>
        </li>
        <li>
          <Link to="/careupdatesone">CareUpdatesOne</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
